name: Setup Flask App with DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Download DLL from fsm_rover
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: Arunrowan-70/fsm_rover
        workflow: c-cpp.yml
        name: libroverfsm-dll
        path: lib/
        branch: main
        workflow_conclusion: success
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug downloaded files
      shell: cmd
      run: dir lib\

    - name: Run Flask App (Test)
      shell: cmd
      run: |
        echo Current directory:
        cd
        echo Listing root directory:
        dir
        echo Changing to project directory:
        cd D:\a\rover_flask_app\rover_flask_app || echo "CD failed"
        echo Verifying lib directory:
        dir lib\
        echo Running Flask app in background...
        start /b python app.py > flask.log 2>&1
        timeout /t 10
        echo Checking Flask server...
        curl http://localhost:5000/ || echo "Curl failed, checking logs..."
        type flask.log
        echo Stopping Flask app...
        taskkill /IM python.exe /F 2>nul || echo "No Flask process to kill"
