name: Setup Flask App with DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Download DLL from fsm_rover
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: Arunrowan-70/fsm_rover
        workflow: build-dll.yml  # Must match the workflow name in fsm_rover
        name: libroverfsm-dll    # Must match the artifact name in fsm_rover
        path: lib/
        branch: main
        workflow_conclusion: success
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug downloaded files
      run: dir lib\
      shell: cmd  # Ensure dir works correctly

    - name: Run Flask App (Test)
      shell: cmd
      run: |
        echo Starting Flask app...
        python app.py > flask.log 2>&1 &
        timeout /t 10  # Wait 10 seconds for server to start
        curl http://localhost:5000/ || echo "Curl failed, checking logs..."
        type flask.log  # Show Flask output for debugging
